# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_icon', models.ImageField(upload_to='icon')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
